/**
 * AUTO-GENERATED by scripts/sync-app-config.js — đừng sửa tay.
 * Sửa nguồn: config/app-config.js rồi chạy sync.
 */
const TIMDIEMBAN_CONFIG = {
  APP_ORIGIN: "http://localhost:3000",
  NEWS_ORIGIN: "http://localhost:3001",
  SEARCH_ORIGIN: "http://localhost:3000",
  MAPS_AUTO_FOCUS_MINUTES: 2,
  MAPS_AUTO_REOPEN_MAX: 5,
  EXTENSION_INSTALL_URL: ""
};
if (typeof module !== "undefined" && module.exports) {
  module.exports = TIMDIEMBAN_CONFIG;
}
if (typeof globalThis !== "undefined") {
  globalThis.TIMDIEMBAN_CONFIG = TIMDIEMBAN_CONFIG;
}
