/**
 * AUTO-GENERATED by scripts/sync-app-config.js — đừng sửa tay.
 * Sửa nguồn: config/app-config.js rồi chạy sync.
 * Trên trang http(s): APP/NEWS/SEARCH = location.origin (không ép findmap.vn).
 * Extension popup: fallback từ sync (không có location trang web).
 */
function __findmapPageOrigin(fallback) {
  try {
    if (typeof location !== "undefined") {
      const o = String(location.origin || "");
      if (o && /^https?:$/i.test(location.protocol || "")) return o;
    }
  } catch {}
  return String(fallback || "").replace(/\/+$/, "");
}
const TIMDIEMBAN_CONFIG = {
  APP_ORIGIN: __findmapPageOrigin("https://findmap.vn"),
  NEWS_ORIGIN: __findmapPageOrigin("https://findmap.vn"),
  SEARCH_ORIGIN: __findmapPageOrigin("https://findmap.vn"),
  MAPS_AUTO_FOCUS_MINUTES: 2,
  MAPS_AUTO_REOPEN_MAX: 5,
  EXTENSION_INSTALL_URL: ""
};
if (typeof module !== "undefined" && module.exports) {
  module.exports = TIMDIEMBAN_CONFIG;
}
if (typeof globalThis !== "undefined") {
  globalThis.TIMDIEMBAN_CONFIG = TIMDIEMBAN_CONFIG;
}
